apiVersion: v1
kind: Service
metadata:
  name: authorization-station
  labels:
    app: authorization-station
spec:
  selector:
    app: authorization-station
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
